import json
import os

os.makedirs("public/quizzes", exist_ok=True)

def create_quiz(chapter_num, questions_data):
    formatted = []
    for q in questions_data:
        formatted.append({
            "id": str(q["id"]),
            "question": q["q"],
            "options": [
                {"id": "A", "text": q["opts"][0]},
                {"id": "B", "text": q["opts"][1]},
                {"id": "C", "text": q["opts"][2]},
                {"id": "D", "text": q["opts"][3]}
            ],
            "difficulty": q["diff"],
            "correctAnswerId": q["ans"],
            "explanation": q["exp"]
        })
    
    filepath = f"public/quizzes/class-8-mathematics-chapter-{chapter_num}.json"
    with open(filepath, "w", encoding="utf-8") as f:
        json.dump({"questions": formatted}, f, indent=2, ensure_ascii=False)
    print(f"Generated {filepath} with {len(formatted)} questions.")

ch9 = [
  {"id":1,"diff":"Easy","q":"The widely utilized theorem $a^2 + b^2 = c^2$ applies exclusively to which specific type of geometric triangle?","opts":["Equilateral","Isosceles","Right-angled","Scalene"],"ans":"C","exp":"The Pythagorean theorem applies only to right-angled triangles."},
  {"id":2,"diff":"Easy","q":"Within the theorem formula $a^2 + b^2 = c^2$, what does the variable 'c' invariably represent?","opts":["Altitude","Base","Hypotenuse","Right angle"],"ans":"C","exp":"In the theorem, 'c' is the length of the hypotenuse."},
  {"id":3,"diff":"Easy","q":"Geometrically, the hypotenuse is unequivocally the ________ side of a right triangle.","opts":["Shortest","Longest","Vertical","Horizontal"],"ans":"B","exp":"The hypotenuse, being opposite the 90° angle, is always the longest side."},
  {"id":4,"diff":"Easy","q":"The ancient Indian mathematician historically credited with stating this specific theorem well before Pythagoras is:","opts":["Aryabhata","Bhaskaracharya","Baudhayana","Ramanujan"],"ans":"C","exp":"Baudhayana stated the theorem in the Sulba Sutras."},
  {"id":5,"diff":"Easy","q":"A specific set of three integers that mathematically satisfy the equation $a^2 + b^2 = c^2$ is historically classified as a:","opts":["Magic triple","Baudhayana triple","Golden ratio","Prime trio"],"ans":"B","exp":"A set of three integers satisfying this theorem is known as a Pythagorean or Baudhayana triple."},
  {"id":6,"diff":"Easy","q":"If the two shorter sides of a right triangle measure 3 and 4, what is the length of the hypotenuse?","opts":["5","6","7","25"],"ans":"A","exp":"Using the theorem: $3^2 + 4^2 = 9 + 16 = 25$. $\\sqrt{25} = 5$."},
  {"id":7,"diff":"Easy","q":"Evaluate the basic arithmetic expression $3^2 + 4^2$.","opts":["7","14","25","49"],"ans":"C","exp":"$3^2 + 4^2 = 9 + 16 = 25$."},
  {"id":8,"diff":"Easy","q":"In ancient Indian mathematical texts, this specific theorem was heavily utilized to construct what specific shapes for ceremonial fire altars?","opts":["Perfect circles","Spheres","Squares","Kites"],"ans":"C","exp":"The theorem was used to construct accurate geometric shapes, particularly squares for fire altars."},
  {"id":9,"diff":"Easy","q":"Doubling the strict side length of any square makes its total internal area how many times larger?","opts":["2","3","4","8"],"ans":"C","exp":"Area $= s^2$. If side is $2s$, Area $= (2s)^2 = 4s^2$, which is 4 times larger."},
  {"id":10,"diff":"Easy","q":"The side positioned directly opposite the 90-degree right angle is officially called the:","opts":["Adjacent","Hypotenuse","Opposite","Vertex"],"ans":"B","exp":"The side directly opposite the right angle is the hypotenuse."},
  {"id":11,"diff":"Medium","q":"If a defined right triangle features shorter sides of exactly 5 cm and 12 cm, what is the length of its hypotenuse?","opts":["13 cm","15 cm","17 cm","19 cm"],"ans":"A","exp":"$5^2 + 12^2 = 25 + 144 = 169$. $\\sqrt{169} = 13$."},
  {"id":12,"diff":"Medium","q":"If a right triangle's hypotenuse measures 15 cm and one leg measures 9 cm, what is the exact length of the third side?","opts":["10 cm","12 cm","14 cm","16 cm"],"ans":"B","exp":"$15^2 - 9^2 = 225 - 81 = 144$. $\\sqrt{144} = 12$."},
  {"id":13,"diff":"Medium","q":"How did the mathematician Baudhayana explicitly instruct one to construct a square possessing double the area of a given square?","opts":["Double all the sides","Construct a new square utilizing the diagonal as the base","Halve all the sides","Draw an inscribed circle"],"ans":"B","exp":"The area of a square constructed on the diagonal of a given square is double the area of the original square."},
  {"id":14,"diff":"Medium","q":"Which of the following integer sets represents a legitimate primitive Baudhayana triple?","opts":["(4, 5, 6)","(6, 8, 10)","(7, 9, 11)","(10, 20, 30)"],"ans":"B","exp":"(6,8,10) satisfies $6^2 + 8^2 = 10^2$ (36+64=100), although it's a scaled version of (3,4,5)."},
  {"id":15,"diff":"Medium","q":"The exact length of the hypotenuse of an isosceles right triangle featuring a small side length of 'a' is:","opts":["2a","a√2","a²","a/2"],"ans":"B","exp":"Using theorem: $a^2 + a^2 = 2a^2$. Hypotenuse = $\\sqrt{2a^2} = a\\sqrt{2}$."},
  {"id":16,"diff":"Medium","q":"If a specific isosceles right triangle possesses a hypotenuse measuring 6√2 cm, what are the precise lengths of its other two identical sides?","opts":["3 cm","6 cm","12 cm","36 cm"],"ans":"B","exp":"Since hypotenuse is $a\\sqrt{2}$, if it is $6\\sqrt{2}$, then $a = 6$ cm."},
  {"id":17,"diff":"Medium","q":"A physical ladder rests against a vertical wall. The ladder itself is 10 m long and its foot sits 6 m from the wall's base. How high up the wall does the ladder reach?","opts":["4 m","6 m","8 m","12 m"],"ans":"C","exp":"$10^2 - 6^2 = 100 - 36 = 64$. $\\sqrt{64} = 8$ m."},
  {"id":18,"diff":"Medium","q":"Mathematically verify if the set (8, 15, 17) constitutes a valid Baudhayana triple.","opts":["Yes, because 64+225=289","No, because 64+225 ≠ 289","Yes, simply because 8+15=17","Cannot be verified with current methods"],"ans":"A","exp":"$8^2 + 15^2 = 64 + 225 = 289$. $17^2 = 289$."},
  {"id":19,"diff":"Medium","q":"Calculate the precise diagonal measurement of a square featuring a side length of 5 cm.","opts":["5 cm","5√2 cm","10 cm","25 cm"],"ans":"B","exp":"Diagonal of square = $side \\times \\sqrt{2} = 5\\sqrt{2}$."},
  {"id":20,"diff":"Medium","q":"In standard geometric definitions, the diagonals of a rhombus bisect each other at what specific angle?","opts":["45°","60°","90°","120°"],"ans":"C","exp":"Diagonals of a rhombus always intersect at a 90° angle."},
  {"id":21,"diff":"Hard","q":"Deduce the exact side length of a rhombus whose two internal diagonals measure 16 cm and 12 cm respectively.","opts":["10 cm","14 cm","20 cm","28 cm"],"ans":"A","exp":"Diagonals bisect at 90°, forming right triangles with legs 8 cm and 6 cm. Side = $\\sqrt{8^2 + 6^2} = \\sqrt{64+36} = \\sqrt{100} = 10$ cm."},
  {"id":22,"diff":"Hard","q":"According to Fermat's Last Theorem, does the algebraic equation $x^n + y^n = z^n$ possess any positive integer solutions for conditions where n > 2?","opts":["Yes, an infinite number","Yes, exactly one","No valid integer solutions exist","Only exists for prime values of n"],"ans":"C","exp":"Fermat's Last Theorem states there are no positive integer solutions for $n > 2$."},
  {"id":23,"diff":"Hard","q":"Based on Bhaskaracharya's classical lotus problem: A 13-unit rigid stem protrudes exactly 5 units above the water line. Wind blows it such that the tip just touches the water's surface. What is the calculated depth of the water?","opts":["5 units","8 units","12 units","13 units"],"ans":"B","exp":"Total length = 13. Let depth = x. $x + 5 = 13 \\implies x = 8$. (This evaluates depth based on problem statement logic provided)."},
  {"id":24,"diff":"Hard","q":"Referencing the same lotus problem, mathematically deduce how far the tip moved laterally from its original vertical position.","opts":["√89 units","√105 units","12 units","13 units"],"ans":"B","exp":"Using a right triangle with hypotenuse 13 (stem length) and depth 8. Lateral distance $d^2 + 8^2 = 13^2 \\implies d^2 = 169 - 64 = 105$. $d = \\sqrt{105}$."},
  {"id":25,"diff":"Hard","q":"To successfully halve a square's total area, the mathematician Baudhāyana geometrically suggested:","opts":["Drawing a smaller square internally aligned directly with the original diagonals","Slicing the square laterally in half","Dividing all perimeter side lengths by 2","Inscribing circular arcs"],"ans":"A","exp":"Baudhayana described halving a square's area by constructing a square whose side is half the diagonal of the original."},
  {"id":26,"diff":"Hard","q":"If the integer set (a, b, c) represents a primitive triple, will the mathematically scaled set (ka, kb, kc) also function universally as a valid triple for any positive integer k?","opts":["Yes","No","Only if k is a prime number","Only if k is an even number"],"ans":"A","exp":"Yes, $(ka)^2 + (kb)^2 = k^2a^2 + k^2b^2 = k^2(a^2 + b^2) = k^2c^2 = (kc)^2$."},
  {"id":27,"diff":"Hard","q":"Calculating the area of a perfect equilateral triangle featuring a side length of 6 units requires first deducing its altitude. What is this exact altitude?","opts":["3","3√3","6","9"],"ans":"B","exp":"Altitude bisects base into 3. Altitude $h^2 + 3^2 = 6^2 \\implies h^2 = 36 - 9 = 27$. $h = \\sqrt{27} = 3\\sqrt{3}$."},
  {"id":28,"diff":"Hard","q":"Which ancient historical text provides detailed instructions on how to construct a new square whose area is exactly triple the area of a given square?","opts":["Arthashastra","Sulba-Sutra","Rigveda","Upanishads"],"ans":"B","exp":"The Sulba Sutras provide precise geometric constructions for altars, including squares with multiple area relationships."},
  {"id":29,"diff":"Hard","q":"Analyzing the algebraic equation $(x+2)^2 = (x-2)^2 + x^2$, what exact numerical value does x represent if it denotes the side of a physical right triangle?","opts":["4","8","12","16"],"ans":"B","exp":"$x^2 + 4x + 4 = x^2 - 4x + 4 + x^2 \\implies 8x = x^2$. Since $x > 0$, $x = 8$."},
  {"id":30,"diff":"Hard","q":"If an identified scaled mathematical triple is (16, 30, 34), what was the foundational primitive triple from which it was derived?","opts":["(4, 7.5, 8.5)","(8, 15, 17)","(32, 60, 68)","(3, 4, 5)"],"ans":"B","exp":"Divide each term by their greatest common divisor (2): $16/2 = 8$, $30/2 = 15$, $34/2 = 17$."}
]

ch10 = [
  {"id":1,"diff":"Easy","q":"In a strict inverse proportion relationship, if one specific quantity increases, the corresponding connected quantity must:","opts":["Increase","Decrease","Stay exactly the same","Become zero"],"ans":"B","exp":"Inverse proportion means as one goes up, the other goes down proportionately."},
  {"id":2,"diff":"Easy","q":"Which visual statistical graph utilizes slices of a circle to denote proportional data?","opts":["Bar graph","Line graph","Pie chart","Dot plot"],"ans":"C","exp":"Pie charts use circle slices to represent portions of a whole."},
  {"id":3,"diff":"Easy","q":"The total geometric angle situated at the center of any pie chart is always:","opts":["90°","180°","270°","360°"],"ans":"D","exp":"A full circle is exactly 360°."},
  {"id":4,"diff":"Easy","q":"The foundational algebraic equation for inverse proportion is commonly expressed as:","opts":["y = kx","xy = k","y = x+k","y = x/k"],"ans":"B","exp":"For inverse proportions, the product of the two variables remains constant: $x \\times y = k$."},
  {"id":5,"diff":"Easy","q":"If exactly 20 workers require 4 days to finalize a job, 10 workers working at the same pace will require:","opts":["2 days","4 days","8 days","16 days"],"ans":"C","exp":"Inverse proportion: $(20)(4) = 80$ worker-days. For 10 workers, $80 / 10 = 8$ days."},
  {"id":6,"diff":"Easy","q":"Standard map scales are frequently written as an RF. What does the acronym RF stand for?","opts":["Ratio Factor","Representative Fraction","Real Figure","Relative Form"],"ans":"B","exp":"RF stands for Representative Fraction (e.g., 1:1000)."},
  {"id":7,"diff":"Easy","q":"A specific ratio composed of 1:3:5 contains exactly how many total parts?","opts":["3","8","9","15"],"ans":"C","exp":"Total parts $= 1 + 3 + 5 = 9$."},
  {"id":8,"diff":"Easy","q":"Within a pie chart, a 90° slice geometrically represents what specific fraction of the entire whole?","opts":["1/2","1/3","1/4","1/8"],"ans":"C","exp":"$90 / 360 = 1/4$."},
  {"id":9,"diff":"Easy","q":"Which of the following real-world relationships is definitively inversely proportional?","opts":["Number of apples bought and total cost","Speed of a vehicle and time taken for a fixed trip","Distance traveled and time elapsed at a constant speed","A person's height and weight"],"ans":"B","exp":"Higher speed means less time taken for the same fixed distance."},
  {"id":10,"diff":"Easy","q":"In a multi-term mathematical ratio such as a:b:c, is it permissible for the terms to be scaled simultaneously by the exact same numerical factor?","opts":["Yes","No","Only by a factor of 2","Only utilizing fractions"],"ans":"A","exp":"Multiplying all parts of a ratio by a constant non-zero factor does not change the proportion."},
  {"id":11,"diff":"Medium","q":"If a standard map utilizes a scale of 1:6,000,000, what actual physical ground distance does 2.5 cm on the map represent?","opts":["15 km","150 km","1500 km","25 km"],"ans":"B","exp":"$2.5 \\text{ cm} \\times 6,000,000 = 15,000,000 \\text{ cm} = 150,000 \\text{ m} = 150 \\text{ km}$."},
  {"id":12,"diff":"Medium","q":"Exactly 110 units of construction concrete are mixed in the precise ratio of 1:1.5:3. How much gravel (representing the 3 parts) is required?","opts":["20","30","60","90"],"ans":"C","exp":"Total parts $= 1 + 1.5 + 3 = 5.5$. Value of 1 part $= 110 / 5.5 = 20$. Gravel $= 3 \\times 20 = 60$ units."},
  {"id":13,"diff":"Medium","q":"I possess 100 coins structured in the ratio ₹10 : ₹5 : ₹2 : ₹1 = 4:3:2:1. How many specific ₹10 coins do I hold?","opts":["10","20","30","40"],"ans":"D","exp":"Total ratio parts $= 4 + 3 + 2 + 1 = 10$. Value of 1 part $= 100 / 10 = 10$. ₹10 coins (4 parts) $= 4 \\times 10 = 40$."},
  {"id":14,"diff":"Medium","q":"Construct a pie chart representing 360 surveyed individuals: 90 prefer summer, 120 rainy, 150 winter. What is the central angle for the summer sector?","opts":["90°","120°","150°","180°"],"ans":"A","exp":"Total $= 360$. Summer angle $= (90 / 360) \\times 360 = 90°$."},
  {"id":15,"diff":"Medium","q":"A group of 80 students possesses enough food for 15 days. If 20 additional students join the group, how many days will the identical food supply last?","opts":["10 days","12 days","18 days","20 days"],"ans":"B","exp":"Total food $= 80 \\times 15 = 1200$ portions. For 100 students, $1200 / 100 = 12$ days."},
  {"id":16,"diff":"Medium","q":"Exactly 2 identical water pumps fill a storage tank in 18 hours. 4 identical pumps will fill the same tank in:","opts":["9 hours","12 hours","36 hours","72 hours"],"ans":"A","exp":"Inverse proportion: $2 \\times 18 = 36$ pump-hours. $36 / 4 = 9$ hours."},
  {"id":17,"diff":"Medium","q":"A triangle's three internal angles exist in the ratio 1:3:5. What is the precise measure of the largest angle?","opts":["20°","60°","100°","120°"],"ans":"C","exp":"Total parts $= 1 + 3 + 5 = 9$. Sum of angles $= 180°$. One part $= 180 / 9 = 20°$. Largest $= 5 \\times 20 = 100°$."},
  {"id":18,"diff":"Medium","q":"Mathematically verify if the coordinate pairs x and y are in inverse proportion: (40, 20) and (80, 10).","opts":["Yes, because 40 × 20 = 80 × 10","No, because the direct ratios differ","They are in direct proportion","Cannot be determined definitively"],"ans":"A","exp":"$40 \\times 20 = 800$, and $80 \\times 10 = 800$. Since product is constant, they are inversely proportional."},
  {"id":19,"diff":"Medium","q":"Within a demographic pie chart, the 'Entertainment' sector accounts for 50%. What is its precise central angle?","opts":["50°","90°","180°","360°"],"ans":"C","exp":"$50\\% \\text{ of } 360° = 0.5 \\times 360 = 180°$."},
  {"id":20,"diff":"Medium","q":"If worker Ram completes 1 unit/hr and worker Shyam completes 2/3 unit/hr, their combined collaborative work rate is:","opts":["1/3 units/hr","5/3 units/hr","3/5 units/hr","2 units/hr"],"ans":"B","exp":"Combined rate $= 1 + 2/3 = 3/3 + 2/3 = 5/3$ units/hr."},
  {"id":21,"diff":"Hard","q":"Is it geometrically possible to construct a valid physical triangle featuring side lengths in the precise ratio of 1:3:5?","opts":["Yes, because angles can add to 180","No, because 1+3 < 5 explicitly violates the triangle inequality theorem","Yes, provided it is a right triangle","Yes, provided it is scalene"],"ans":"B","exp":"Triangle inequality theorem states sum of two shorter sides must be strictly greater than third side. $1+3$ is not greater than $5$."},
  {"id":22,"diff":"Hard","q":"If x: 16, 12 and y: 9, blank are inversely proportional (where product xy is constant), what is the missing value?","opts":["12","6.75","27","36"],"ans":"A","exp":"$16 \\times 9 = 144$. So $12 \\times y = 144 \\implies y = 12$."},
  {"id":23,"diff":"Hard","q":"Three distinct unknown numbers exist in the ratio 1:2:3. Their calculated product is exactly 1296. What is the numerical sum of these three numbers?","opts":["18","36","54","72"],"ans":"B","exp":"Let numbers be $x, 2x, 3x$. Product $= 6x^3 = 1296 \\implies x^3 = 216 \\implies x = 6$. Sum $= 6 + 12 + 18 = 36$."},
  {"id":24,"diff":"Hard","q":"An isolated camp of 200 soldiers holds food provisions for 200 days. After exactly 20 days have passed, 100 additional soldiers join. For how many subsequent days will the remaining food last?","opts":["80 days","100 days","120 days","150 days"],"ans":"C","exp":"Food remaining $= 200 \\times 180 = 36,000$ soldier-days. New troop size $= 300$. Duration $= 36,000 / 300 = 120$ days."},
  {"id":25,"diff":"Hard","q":"Industrial pipes P and Q fill a tank in 12 and 36 hours individually. If activated together simultaneously, they take:","opts":["6 hours","9 hours","12 hours","24 hours"],"ans":"B","exp":"Rate $P = 1/12$. Rate $Q = 1/36$. Combined $= 1/12 + 1/36 = 3/36 + 1/36 = 4/36 = 1/9$. Time $= 9$ hours."},
  {"id":26,"diff":"Hard","q":"In the pie chart problem concerning 100 coins of total value ₹600 (ratio 4:3:2:1 for ₹10, ₹5, ₹2, ₹1 respectively), what is the central geometric angle for the ₹5 coin sector?","opts":["30°","72°","108°","144°"],"ans":"C","exp":"Total coins = 100. Ratio 4:3:2:1 (10 parts) means 30 coins are ₹5. In pie chart based on number of coins: $30/100 \\times 360 = 108°$."},
  {"id":27,"diff":"Hard","q":"When asserting that 2 pumps require 18 hours via inverse proportion, the mathematical model strictly assumes:","opts":["The tanks leak at a constant rate","The pump rates are perfectly identical and constant","Water evaporates during filling","Time operates in direct proportion to volume"],"ans":"B","exp":"For the basic $xy=k$ model to work reliably, all workers/pumps are assumed identical and constant."},
  {"id":28,"diff":"Hard","q":"If an algebraic ratio a:b:c = 2:3:5 dictates a total liquid volume of exactly 50 ml, find the specific volume for part b.","opts":["10 ml","15 ml","20 ml","25 ml"],"ans":"B","exp":"Total parts $= 10$. 1 part $= 5$ ml. Part $b = 3 \\times 5 = 15$ ml."},
  {"id":29,"diff":"Hard","q":"To accurately calculate the collective work rate of 10 workers, the mathematical model inherently assumes:","opts":["Each individual works at wildly different speeds","Total work inherently increases with more workers","Work is divided equally and individual efficiency remains perfectly constant","Days required are directly proportional to workers"],"ans":"C","exp":"The model relies on constant identical efficiency per worker."},
  {"id":30,"diff":"Hard","q":"If the distance between two cities on a 1:5,000,000 scale map is exactly 4 cm, the actual physical ground distance is:","opts":["20 km","200 km","2000 km","500 km"],"ans":"B","exp":"$4 \\times 5,000,000 = 20,000,000 \\text{ cm} = 200 \\text{ km}$."}
]

ch11 = [
  {"id":1,"diff":"Easy","q":"A visual geometric pattern where smaller identical copies of the same structure repeat endlessly at different scales is formally called a:","opts":["Polygon","Fractal","Circle","Line"],"ans":"B","exp":"A fractal is a complex pattern featuring self-similarity at varying scales."},
  {"id":2,"diff":"Easy","q":"Which 3D solid uniquely features a profile with a perfectly circular outline from every conceivable viewpoint?","opts":["Cube","Cylinder","Sphere","Cone"],"ans":"C","exp":"A sphere is perfectly symmetrical from every angle, always casting a circular shadow."},
  {"id":3,"diff":"Easy","q":"A flat, unfolded 2D pattern that can be precisely folded to form a 3D solid is termed a:","opts":["Net","Web","Grid","Map"],"ans":"A","exp":"A geometric net is a 2D layout that folds precisely into a 3D polyhedron."},
  {"id":4,"diff":"Easy","q":"Two geometric figures possessing exactly the same shape and exactly the same size are:","opts":["Similar","Congruent","Tessellations","Fractals"],"ans":"B","exp":"Congruent figures are identical in both shape and size."},
  {"id":5,"diff":"Easy","q":"Two geometric figures possessing the exact same shape but distinctly different sizes are:","opts":["Similar","Congruent","Equal","Parallel"],"ans":"A","exp":"Similar figures have identical shape (equal angles and proportional sides) but may differ in size."},
  {"id":6,"diff":"Easy","q":"Sliding a geometric figure in any direction without any form of rotation is defined as:","opts":["Reflection","Rotation","Translation","Dilation"],"ans":"C","exp":"A translation slides a figure laterally or vertically without twisting it."},
  {"id":7,"diff":"Easy","q":"A 3D solid whose physical profile from the top is a circle and from the side is a triangle is undoubtedly a:","opts":["Cube","Sphere","Cone","Cylinder"],"ans":"C","exp":"A cone features a circular base (top-down view) and slopes up to a point (triangle from side view)."},
  {"id":8,"diff":"Easy","q":"Which famous mathematical fractal triangle is generated by recursively removing the central inverted triangle?","opts":["Pascal's Triangle","Sierpinski Triangle","Koch Triangle","Isosceles Triangle"],"ans":"B","exp":"The Sierpinski Triangle is formed by repeatedly removing the central triangular area."},
  {"id":9,"diff":"Easy","q":"Which specific geometric transformation actively changes the size/scale of the figure?","opts":["Translation","Reflection","Rotation","Dilation"],"ans":"D","exp":"Dilation resizes the object, either shrinking or enlarging it."},
  {"id":10,"diff":"Easy","q":"A geometric pattern where shapes fit together flawlessly with absolutely no gaps or overlaps is a:","opts":["Fractal","Tessellation","Projection","Reflection"],"ans":"B","exp":"A tessellation (or tiling) completely covers a plane without any gaps or overlap."},
  {"id":11,"diff":"Medium","q":"In constructing the Sierpinski Triangle, exactly how many smaller solid triangles remain after Step 1?","opts":["1","3","4","9"],"ans":"B","exp":"Step 0 is 1 triangle. Step 1 removes the center, leaving 3 smaller triangles."},
  {"id":12,"diff":"Medium","q":"Following the rules of the Sierpinski Triangle, how many solid triangles remain at Step 2?","opts":["6","9","12","27"],"ans":"B","exp":"Each of the 3 triangles from Step 1 becomes 3 smaller triangles: $3 \\times 3 = 9$."},
  {"id":13,"diff":"Medium","q":"The Koch Snowflake generation sequence universally initiates with which base shape?","opts":["Square","Circle","Equilateral Triangle","Hexagon"],"ans":"C","exp":"The Koch Snowflake always starts with a solid equilateral triangle."},
  {"id":14,"diff":"Medium","q":"In the Koch Snowflake Step 1 iteration, how many total sides does the resultant shape possess?","opts":["3","6","9","12"],"ans":"D","exp":"The original 3 sides each become 4 shorter segments. $3 \\times 4 = 12$ sides."},
  {"id":15,"diff":"Medium","q":"If a standard 3D cube is viewed directly and flatly from one face, its 2D optical projection is a:","opts":["Rectangle","Square","Hexagon","Rhombus"],"ans":"B","exp":"Looking perfectly perpendicular to one face of a cube produces a square profile."},
  {"id":16,"diff":"Medium","q":"If a cube is tilted perfectly to look directly down one of its corners (body diagonal), its outer boundary silhouette forms a:","opts":["Triangle","Square","Hexagon","Octagon"],"ans":"C","exp":"Viewing a cube along its main internal diagonal projects a regular hexagon."},
  {"id":17,"diff":"Medium","q":"A pyramid features a polygonal base and an apex. If two square pyramids are joined perfectly at their bases, the resulting solid is an:","opts":["Icosahedron","Octahedron","Hexahedron","Dodecahedron"],"ans":"B","exp":"Two square pyramids joined at their bases create a regular octahedron (8 triangular faces)."},
  {"id":18,"diff":"Medium","q":"Which regular mathematical polygon cannot form a tessellation strictly by itself?","opts":["Equilateral Triangle","Square","Regular Hexagon","Regular Pentagon"],"ans":"D","exp":"A regular pentagon has an interior angle of 108°, which does not divide evenly into 360°, thus leaving gaps."},
  {"id":19,"diff":"Medium","q":"Historic Indian architectural marvels like the Kandariya Mahadev Temple exhibit structural self-similarity akin to modern:","opts":["Fractals","Tessellations","Projections","Nets"],"ans":"A","exp":"The temple's tiered spires repeat the main spire shape at varying smaller scales, mirroring fractals."},
  {"id":20,"diff":"Medium","q":"In the Sierpinski Carpet sequence, a square is divided into 9 smaller squares and the center is discarded. How many squares remain in Step 1?","opts":["7","8","9","10"],"ans":"B","exp":"$9 - 1 \\text{ (center)} = 8$ remaining squares."},
  {"id":21,"diff":"Hard","q":"What is the calculated area of the remaining solid region at the $n^{th}$ step of the Sierpinski Triangle (assuming the initial step 0 area is exactly 1)?","opts":["(1/3)^n","(2/3)^n","(3/4)^n","(4/3)^n"],"ans":"C","exp":"At each step, 1/4 of each solid triangle's area is removed, leaving 3/4. After n steps, area is $(3/4)^n$."},
  {"id":22,"diff":"Hard","q":"The exact mathematical number of sides present in the $n^{th}$ step of the Koch Snowflake is given by the algebraic formula:","opts":["3 × 4^n","4 × 3^n","3 × n^4","3 + 4n"],"ans":"A","exp":"Step 0 has 3 sides. Each step multiplies the number of sides by 4. Thus $3 \\times 4^n$."},
  {"id":23,"diff":"Hard","q":"If the initial Step 0 perimeter of the Koch Snowflake is exactly 3 units, what is the precise perimeter at Step 2?","opts":["3","4","16/3","64/9"],"ans":"C","exp":"Perimeter at Step $n$ is $P_0 \\times (4/3)^n$. $3 \\times (4/3)^2 = 3 \\times 16/9 = 16/3$."},
  {"id":24,"diff":"Hard","q":"When a physical cube is angled symmetrically so its optical outline has 4 equal outer edges but contains no right angles, the projection is definitively a:","opts":["Parallelogram","Rhombus","Rectangle","Hexagon"],"ans":"B","exp":"A rhombus has 4 equal sides but its interior angles are not necessarily 90°."},
  {"id":25,"diff":"Hard","q":"Cutting off the four distinct corners of a square, with cuts traversing exactly between the midpoints of adjacent edges, leaves what specific geometric shape?","opts":["Circle","Smaller square","Octagon","Cross"],"ans":"B","exp":"Connecting the midpoints of a square forms a smaller inscribed square tilted at 45°."},
  {"id":26,"diff":"Hard","q":"If the sides of an equilateral triangle are distinctly marked into thirds and the corners cut off precisely at the marks, the resulting shape is a:","opts":["Circle","Regular Hexagon","Triangle","Nonagon"],"ans":"B","exp":"Truncating the corners of an equilateral triangle cleanly at one-third points produces a regular hexagon."},
  {"id":27,"diff":"Hard","q":"The perimeter of the Koch Snowflake mathematically approaches infinity, but its total bounded area:","opts":["Also approaches infinity","Becomes absolutely zero","Remains finite","Becomes negative"],"ans":"C","exp":"Despite an infinitely long perimeter, the area converges to exactly $8/5$ of the original triangle's area."},
  {"id":28,"diff":"Hard","q":"Which specific type of drafting projection aids designers in drawing 3D shapes where all edges of a cube appear strictly equal in length?","opts":["Orthographic","Isometric","Perspective","Topological"],"ans":"B","exp":"Isometric projection displays all three axes equally scaled (at 120° apart)."},
  {"id":29,"diff":"Hard","q":"To geometrically create a new square with an area equal to the difference of the areas of squares of sides 7 and 5, one would employ:","opts":["Fractal geometry","Baudhayana-Pythagoras Theorem","Projections","Nets"],"ans":"B","exp":"By constructing a right triangle where hypotenuse is 7 and one leg is 5, the other leg satisfies $x^2 = 7^2 - 5^2$."},
  {"id":30,"diff":"Hard","q":"The Koch Snowflake generation process recursively replaces each individual line segment with exactly how many new, smaller segments?","opts":["2","3","4","5"],"ans":"C","exp":"Each straight segment is divided into 3, and the middle section is replaced by 2 sides of an equilateral triangle, totaling 4 smaller segments."}
]

ch12 = [
  {"id":1,"diff":"Easy","q":"The mathematical 'center' of a set of statistical data is frequently represented by the:","opts":["Range","Mean","Maximum","Minimum"],"ans":"B","exp":"The mean is the arithmetic average, acting as the mathematical center or balance point of data."},
  {"id":2,"diff":"Easy","q":"Within a standard dot plot, what does each individual dot represent?","opts":["A missing value","A single data point observation","The calculated mean","The calculated median"],"ans":"B","exp":"Each physical dot on the axis corresponds to exactly one observed data value."},
  {"id":3,"diff":"Easy","q":"How does one precisely find the arithmetic mean of exactly two numbers?","opts":["Add them","Subtract them","Add them and divide the sum by 2","Multiply them"],"ans":"C","exp":"Sum the values and divide by the count: $(a + b) / 2$."},
  {"id":4,"diff":"Easy","q":"What is the calculated mean of the numbers 3 and 7?","opts":["4","5","10","21"],"ans":"B","exp":"$(3 + 7) / 2 = 10 / 2 = 5$."},
  {"id":5,"diff":"Easy","q":"The designated origin on a standard 2D coordinate plane is the point:","opts":["(1,1)","(0,1)","(1,0)","(0,0)"],"ans":"D","exp":"The origin is where the x and y axes intersect, representing coordinates $(0,0)$."},
  {"id":6,"diff":"Easy","q":"In a standard graph, the horizontal line is conventionally labeled the:","opts":["x-axis","y-axis","z-axis","origin"],"ans":"A","exp":"The horizontal axis is universally standard as the x-axis."},
  {"id":7,"diff":"Easy","q":"Which specific statistical graph utilizes a continuous line to denote changes over a period of time?","opts":["Bar graph","Pie chart","Line graph","Histogram"],"ans":"C","exp":"Line graphs are perfectly suited to show trends and continuous changes over time intervals."},
  {"id":8,"diff":"Easy","q":"The exact middle value of an ordered statistical data set is formally called the:","opts":["Mean","Mode","Median","Range"],"ans":"C","exp":"When data is sorted by size, the central value separating higher and lower halves is the median."},
  {"id":9,"diff":"Easy","q":"Nodes and edges are distinct terms utilized heavily in:","opts":["Algebra","Graph Theory","Arithmetic","Calculus"],"ans":"B","exp":"In mathematical graph theory, points are nodes (or vertices) connected by lines called edges."},
  {"id":10,"diff":"Easy","q":"To accurately plot the coordinate (3, -2), you move from the origin:","opts":["Right 3, Up 2","Right 3, Down 2","Left 3, Down 2","Up 3, Right 2"],"ans":"B","exp":"Positive x moves right (3), negative y moves down (2)."},
  {"id":11,"diff":"Medium","q":"If you intentionally add a new number greater than the current mean to a data set, the new mean will definitively:","opts":["Decrease","Increase","Stay the same","Become zero"],"ans":"B","exp":"Adding a value higher than the average logically pulls the new balance point (mean) higher."},
  {"id":12,"diff":"Medium","q":"A dot plot displays values: 4, 7, 8, 8, 9, 9, 9, 9, 9, 11, and x. If the required mean is exactly 9, what is the value of x?","opts":["9","11","16","20"],"ans":"C","exp":"Sum without x $= 83$. Total data points $= 11$. For mean $= 9$, Total sum must be $9 \\times 11 = 99$. Thus $x = 99 - 83 = 16$."},
  {"id":13,"diff":"Medium","q":"The calculated mean of exactly 15 values is 134. What is the total sum of all 15 values?","opts":["149","1000","2010","2500"],"ans":"C","exp":"Total sum $=$ Mean $\\times$ Count $= 134 \\times 15 = 2010$."},
  {"id":14,"diff":"Medium","q":"If every single value in a dataset is uniformly increased by 10, the new mean will:","opts":["Increase by exactly 10","Decrease by exactly 10","Multiply by 10","Stay exactly the same"],"ans":"A","exp":"A uniform translation shifts the entire dataset, shifting the mean identically by $+10$."},
  {"id":15,"diff":"Medium","q":"If every single value in a dataset is uniformly multiplied by 5, the new mean will:","opts":["Increase by 5","Be 5 times the old mean","Stay the same","Divide by 5"],"ans":"B","exp":"Scaling the data directly scales the mean by the exact same factor."},
  {"id":16,"diff":"Medium","q":"What is the exact mathematical mean of the first 50 natural numbers?","opts":["25","25.5","26","50"],"ans":"B","exp":"Sum $= (n(n+1))/2$. Mean for contiguous set $= (1+50)/2 = 25.5$."},
  {"id":17,"diff":"Medium","q":"A linear graph representing the equation $y = mx$ always explicitly passes through:","opts":["(0,1)","(1,0)","(0,0)","(1,1)"],"ans":"C","exp":"If $x=0$, $y=m(0)=0$. It passes perfectly through the origin."},
  {"id":18,"diff":"Medium","q":"If you add a new value exactly equal to the existing median to a data set, the new median:","opts":["Increases","Decreases","Stays the same","Doubles"],"ans":"C","exp":"Adding a value equal to the median adds weight exactly at the center, leaving it unchanged."},
  {"id":19,"diff":"Medium","q":"The mean of the numbers 8, 13, 10, 4, 5, 20, y, and 10 is 10.375. Mathematically find y.","opts":["10","13","15","17"],"ans":"B","exp":"Sum $= 70 + y$. Total count $= 8$. $70 + y = 10.375 \\times 8 = 83$. Thus $y = 13$."},
  {"id":20,"diff":"Medium","q":"To calculate the median efficiently from a frequency table, you must first:","opts":["Find the mean","Find cumulative frequencies","Multiply values by frequencies","Draw a pie chart"],"ans":"B","exp":"Cumulative frequencies map exactly where the middle data point lies within the sorted groups."},
  {"id":21,"diff":"Hard","q":"If you have 11 distinct numbers featuring a median of 41, adding which two specific numbers will leave the median entirely unchanged?","opts":["40 and 42","30 and 35","50 and 60","40 and 39"],"ans":"A","exp":"Adding one number below (40) and one number above (42) preserves the exact central balance point index of 41."},
  {"id":22,"diff":"Hard","q":"\"Removing a value less than the median will decrease the median.\" This statement is statistically:","opts":["Always true","Never true","Sometimes true","Mathematically impossible"],"ans":"B","exp":"Removing a value lower than the median actually shifts the center upward, forcing the median to stay the same or increase."},
  {"id":23,"diff":"Hard","q":"In a dot plot, the mean represents the physical balance point. This dictates that:","opts":["The sum of values on LHS equals RHS","The sum of distances from the mean on LHS equals RHS","The number of dots on LHS equals RHS","The median is always equal to the mean"],"ans":"B","exp":"The mean is the fulcrum; total physical deviation (distance) on left strictly balances total deviation on right."},
  {"id":24,"diff":"Hard","q":"If an album's song lengths are 0.5, 0.75, 1.5, 1.5, 2, 3.75, 4.25, and 5 minutes, what is the calculated mean?","opts":["2.41","3.5","4.1","5.57"],"ans":"A","exp":"Sum $= 19.25$. Count $= 8$. $19.25 / 8 \\approx 2.40625$, which rounds to 2.41."},
  {"id":25,"diff":"Hard","q":"Algebraically, if a baseline mean $a = (x_1+x_2+...+x_n)/n$, then multiplying each $x$ by a factor of 5 yields a new mean of:","opts":["a+5","5a","a/5","a^5"],"ans":"B","exp":"$ (5x_1 + 5x_2 + ...) / n = 5(x_1 + x_2 + ...) / n = 5a $."},
  {"id":26,"diff":"Hard","q":"In the genesis of graph theory, the famous Königsberg Bridge problem was elegantly solved utilizing abstract nodes and edges by:","opts":["Pythagoras","Euler","Brahmagupta","Aryabhata"],"ans":"B","exp":"Leonhard Euler essentially invented Graph Theory resolving this bridge problem in 1736."},
  {"id":27,"diff":"Hard","q":"Adding four specific values completely below the median to an existing dataset will:","opts":["Increase the median","Decrease or maintain the median","Make the median exactly zero","Double the median"],"ans":"B","exp":"Adding multiple lower values drags the central midpoint index downwards, resulting in a lower (or identical) median."},
  {"id":28,"diff":"Hard","q":"The coordinate point (-3, 4) lies distinctly in which geometric quadrant?","opts":["I","II","III","IV"],"ans":"B","exp":"Negative $x$ and Positive $y$ places the coordinate perfectly in the upper-left Quadrant II."},
  {"id":29,"diff":"Hard","q":"To find the mean of data provided with frequencies (e.g., 3 students have a family size of 4), you must structurally:","opts":["Add the frequencies","Add the family sizes","Multiply each size by its frequency, sum them, and divide by total students","Find the median instead"],"ans":"C","exp":"Weighted average formula: $\\sum (f_i \\times x_i) / \\sum f_i$."},
  {"id":30,"diff":"Hard","q":"If a linear graph represents distance vs. time at a constant speed, the physical slope of the plotted line directly represents:","opts":["Time","Distance","Speed","Acceleration"],"ans":"C","exp":"Slope $= \\Delta y / \\Delta x = \\text{Distance} / \\text{Time} = \\text{Speed} $."}
]

ch13 = [
  {"id":1,"diff":"Easy","q":"What is a mathematical symbol (like $x$ or $y$) utilized to represent an unknown or varying quantity called?","opts":["Constant","Variable","Equation","Identity"],"ans":"B","exp":"A variable acts as a placeholder for numbers that can change or are unknown."},
  {"id":2,"diff":"Easy","q":"A mathematical expression containing an explicit '=' sign is formally called an:","opts":["Expression","Equation","Inequality","Exponent"],"ans":"B","exp":"An equation asserts mathematical equality between two distinct expressions."},
  {"id":3,"diff":"Easy","q":"What is the precise numerical coefficient of $x$ in the algebraic term $7x^2$?","opts":["x","2","7","14"],"ans":"C","exp":"The coefficient is the constant numerical multiplier at the front, which is 7."},
  {"id":4,"diff":"Easy","q":"If the variable $x = 3$, what is the calculated value of $2x + 1$?","opts":["4","6","7","8"],"ans":"C","exp":"Substitute 3 for $x$: $2(3) + 1 = 6 + 1 = 7$."},
  {"id":5,"diff":"Easy","q":"In a standard mathematical number pyramid, the number in a block is the ________ of the two numbers directly below it.","opts":["Difference","Product","Sum","Quotient"],"ans":"C","exp":"In a basic additive pyramid, blocks sum to create the block resting directly above them."},
  {"id":6,"diff":"Easy","q":"Are the terms $3x$ and $7x$ classified as like terms?","opts":["Yes","No","Only if x is 1","Only if x is even"],"ans":"A","exp":"Yes, they share the exact identical variable part '$x$' raised to the same power."},
  {"id":7,"diff":"Easy","q":"Which of the following is definitively an equation?","opts":["3x + 5","2y - 4","x + 2 = 5","7x"],"ans":"C","exp":"It contains an '=' sign equating two algebraic sides."},
  {"id":8,"diff":"Easy","q":"Are the terms $3x$ and $5y$ classified as like terms?","opts":["Yes","No","Sometimes","Always"],"ans":"B","exp":"No, they feature distinctly different variables ($x$ vs $y$)."},
  {"id":9,"diff":"Easy","q":"Solving an equation essentially means pinpointing the true numerical value of the:","opts":["Constant","Variable","Coefficient","Exponent"],"ans":"B","exp":"Solving identifies the exact number the variable must represent for the equation to be true."},
  {"id":10,"diff":"Easy","q":"The perimeter of a perfect square with a side represented by $s$ is algebraically:","opts":["s²","4s","s+4","2s"],"ans":"B","exp":"Perimeter $= s + s + s + s = 4s$."},
  {"id":11,"diff":"Medium","q":"Solve the linear equation for $x$: $3x + 7 = 22$.","opts":["3","4","5","6"],"ans":"C","exp":"Subtract 7: $3x = 15$. Divide by 3: $x = 5$."},
  {"id":12,"diff":"Medium","q":"In a 3-row number pyramid, the bottom row reads $a, b, c$. The top number is algebraically:","opts":["a+b+c","a+2b+c","2a+b+c","abc"],"ans":"B","exp":"Middle row is $a+b$ and $b+c$. Top is $(a+b) + (b+c) = a + 2b + c$."},
  {"id":13,"diff":"Medium","q":"In a 3-row pyramid, the bottom row has $12, c, 8$. The final top number is 60. What is the value of $c$?","opts":["10","20","30","40"],"ans":"B","exp":"Top $= 12 + 2c + 8 = 20 + 2c$. Equation: $20 + 2c = 60 \\implies 2c = 40 \\implies c = 20$."},
  {"id":14,"diff":"Medium","q":"Correctly factorise the expression: $6x + 9y$.","opts":["3(2x + 3y)","2(3x + 4y)","3xy","15xy"],"ans":"A","exp":"Extract the Greatest Common Divisor, which is 3. $3(2x + 3y)$."},
  {"id":15,"diff":"Medium","q":"Correctly factorise the expression: $x^2 - 9$.","opts":["(x-3)²","(x+3)(x-3)","(x-9)(x+1)","x(x-9)"],"ans":"B","exp":"Difference of squares formula: $a^2 - b^2 = (a-b)(a+b)$. Here, $x^2 - 3^2 = (x-3)(x+3)$."},
  {"id":16,"diff":"Medium","q":"In the trick: Think of a month (M), multiply by 5, add 6, multiply by 4, add 9, multiply by 5, add day (D). The complex algebra simplifies purely to:","opts":["100M + D + 165","50M + D + 100","M + D","100M - D"],"ans":"A","exp":"$ ( (5M + 6) \\times 4 + 9 ) \\times 5 + D = (20M + 24 + 9) \\times 5 + D = 100M + 165 + D$."},
  {"id":17,"diff":"Medium","q":"If a student's final calculated answer in the date trick is exactly 394, what date (M/D) did they choose?","opts":["02/29","02/05","12/25","10/10"],"ans":"A","exp":"Result $= 100M + D + 165$. $100M + D = 394 - 165 = 229$. M is hundreds digit (2, Feb), D is remainder (29). 02/29."},
  {"id":18,"diff":"Medium","q":"If the final answer in the date trick is 1269, what is the precise date?","opts":["11/04","12/04","10/09","01/26"],"ans":"A","exp":"$100M + D = 1269 - 165 = 1104$. M=11 (Nov), D=04."},
  {"id":19,"diff":"Medium","q":"A linear equation graphed on a coordinate plane always appears as a:","opts":["Circle","Parabola","Straight line","Sine wave"],"ans":"C","exp":"Equations of the first degree (like $y = mx+c$) structurally graph as straight lines."},
  {"id":20,"diff":"Medium","q":"Simplify the expanded expression: $ax + ay + bx + by$.","opts":["(a+b)(x+y)","abxy","(a+x)(b+y)","4abxy"],"ans":"A","exp":"Factor by grouping: $a(x+y) + b(x+y) = (a+b)(x+y)$."},
  {"id":21,"diff":"Hard","q":"In a 2x2 mathematical grid, the top left is $a$, top right is $a+1$, bottom left is $a+7$, bottom right is $a+8$. If the aggregate sum is exactly 36, find $a$.","opts":["4","5","6","7"],"ans":"B","exp":"Sum $= a + a+1 + a+7 + a+8 = 4a + 16$. $4a + 16 = 36 \\implies 4a = 20 \\implies a = 5$."},
  {"id":22,"diff":"Hard","q":"If the first four Virahanka-Fibonacci numbers (1, 2, 3, 5) comprise the bottom of a 4-row pyramid, what is the exact top number?","opts":["11","21","31","41"],"ans":"C","exp":"Top block evaluates based on pyramid summation structure."},
  {"id":23,"diff":"Hard","q":"The generalized algebraic formula for the top of a 4-row pyramid with a bottom row of $a, b, c, d$ is:","opts":["a + 3b + 3c + d","a + 2b + 2c + d","a + b + c + d","a + 4b + 4c + d"],"ans":"A","exp":"Expansion follows binomial coefficients: $1, 3, 3, 1$."},
  {"id":24,"diff":"Hard","q":"Deconstruct a \"Think of a Number\" trick: Pick $x$, multiply by 3, add 6, divide by 3, subtract $x$. The answer is algebraically always:","opts":["x","2","3","6"],"ans":"B","exp":"$(3x + 6) / 3 - x = x + 2 - x = 2$. It perfectly cancels the unknown $x$."},
  {"id":25,"diff":"Hard","q":"How do you surgically alter the above trick so the final fixed answer is always 5?","opts":["Add 15 instead of 6","Multiply by 5 initially","Subtract 5 at the end","Divide by 5"],"ans":"A","exp":"$(3x + 15) / 3 - x = x + 5 - x = 5$."},
  {"id":26,"diff":"Hard","q":"If a massive 29-row pyramid features the first 29 Virahanka-Fibonacci numbers at the bottom, the generated numbers inside the pyramid are inherently:","opts":["Prime numbers","Perfect squares","Also Virahanka-Fibonacci numbers","Negative numbers"],"ans":"C","exp":"Due to the additive property $F_{n} + F_{n+1} = F_{n+2}$, the internal numbers inherently follow the same sequence."},
  {"id":27,"diff":"Hard","q":"The algebraic expression $2n - 1$ represents an odd number. The sum of the first $n$ odd numbers universally evaluates to:","opts":["2n","n²","n³","2n-1"],"ans":"B","exp":"$1 + 3 + 5 + ... + (2n-1) = n^2$. This geometrically forms consecutive layers of a square."},
  {"id":28,"diff":"Hard","q":"Using strict algebra, why does the 2x2 grid sum mentioned earlier always exactly equal $4a + 16$?","opts":["Because a + (a+1) + (a+7) + (a+8) = 4a + 16","Because 4 × 4 = 16","It only works for a=5","Due to magic square rules"],"ans":"A","exp":"Simplifying the algebraic addition directly yields the constant expression $4a + 16$."},
  {"id":29,"diff":"Hard","q":"To decode divisibility tricks, algebra shows that a 3-digit number $abc = 100a + 10b + c$. Which rearrangement unequivocally proves divisibility by 9?","opts":["99a + 9b + (a+b+c)","50a + 5b","100a + c","a × b × c"],"ans":"A","exp":"$100a+10b+c = 99a + a + 9b + b + c = (99a+9b) + (a+b+c)$. Since $99a+9b$ is divisible by 9, the number depends entirely on $(a+b+c)$."},
  {"id":30,"diff":"Hard","q":"If you actively solve $(x+3)(x-2) = x^2 + x - 6$, you are deploying the:","opts":["Commutative law","Distributive law","Associative law","Inverse law"],"ans":"B","exp":"Expanding $(x+3)(x-2)$ uses the distributive property multiplying terms across parentheses."}
]

ch14 = [
  {"id":1,"diff":"Easy","q":"The 2D area of a standard rectangle is calculated directly as:","opts":["Length + Width","2 × (Length + Width)","Length × Width","1/2 × Length × Width"],"ans":"C","exp":"Area of rectangle is product of its length and width."},
  {"id":2,"diff":"Easy","q":"What is the calculated area of a square featuring a side of 4 cm?","opts":["8 cm²","12 cm²","16 cm²","20 cm²"],"ans":"C","exp":"Area $= s^2 = 4 \\times 4 = 16\\text{ cm}^2$."},
  {"id":3,"diff":"Easy","q":"The flat, 2D space enclosed by a geometric shape is technically its:","opts":["Perimeter","Volume","Area","Surface Area"],"ans":"C","exp":"Area represents the interior 2D geometric space."},
  {"id":4,"diff":"Easy","q":"The standard formula for the area of a parallelogram is:","opts":["Base × Height","1/2 × Base × Height","Length × Width","4 × Side"],"ans":"A","exp":"Area $= \\text{Base} \\times \\text{Perpendicular Height}$."},
  {"id":5,"diff":"Easy","q":"The standard formula for the area of a triangle is:","opts":["Base × Height","1/2 × Base × Height","Base + Height","Base² × Height²"],"ans":"B","exp":"A triangle is exactly half the area of a parallelogram enclosing it."},
  {"id":6,"diff":"Easy","q":"If a rectangle possesses sides of 7 cm and 4 cm, its area is:","opts":["11 cm²","22 cm²","28 cm²","49 cm²"],"ans":"C","exp":"$7 \\times 4 = 28$ cm²."},
  {"id":7,"diff":"Easy","q":"The linear distance entirely around the outside of a shape is its:","opts":["Area","Volume","Perimeter","Capacity"],"ans":"C","exp":"Perimeter measures the 1D outer boundary length."},
  {"id":8,"diff":"Easy","q":"Is it mathematically possible for two shapes to possess the exact same perimeter but distinctly different areas?","opts":["Yes","No","Only if they are circles","Only if they are squares"],"ans":"A","exp":"Yes. A $1 \\times 9$ rectangle and a $5 \\times 5$ square both have perimeter 20, but areas 9 and 25."},
  {"id":9,"diff":"Easy","q":"The measurement unit for area is always inherently:","opts":["Cubed","Squared","Linear","Metric"],"ans":"B","exp":"Area is 2D, thus its units are always squared (e.g., cm²)."},
  {"id":10,"diff":"Easy","q":"A single diagonal line divides a rectangle into exactly how many equal, congruent triangles?","opts":["2","3","4","8"],"ans":"A","exp":"Cutting diagonally creates 2 identical right triangles."},
  {"id":11,"diff":"Medium","q":"If a parallelogram has a base measuring 5 cm and a height measuring 3 cm, its area is:","opts":["7.5 cm²","8 cm²","15 cm²","30 cm²"],"ans":"C","exp":"Area $= b \\times h = 5 \\times 3 = 15$ cm²."},
  {"id":12,"diff":"Medium","q":"Two distinct rectangles have a perimeter of 22 cm. One is $8 \\times 3$, the other is $7 \\times 4$. What are their respective areas?","opts":["Both 24","Both 28","24 and 28","11 and 22"],"ans":"C","exp":"Area 1 $= 8 \\times 3 = 24$. Area 2 $= 7 \\times 4 = 28$."},
  {"id":13,"diff":"Medium","q":"If a rectangle's sides are 8 cm and 3 cm, and a diagonal divides it into two distinct triangles, what is the area of exactly ONE of those triangles?","opts":["12 cm²","24 cm²","36 cm²","48 cm²"],"ans":"A","exp":"Area of rectangle $= 24$. One triangle $= 24 / 2 = 12$ cm²."},
  {"id":14,"diff":"Medium","q":"The area of a rhombus can be efficiently calculated utilizing its diagonals ($d_1, d_2$) as:","opts":["d1 × d2","1/2 × (d1 + d2)","1/2 × d1 × d2","2 × d1 × d2"],"ans":"C","exp":"Area of a rhombus based on diagonals is $\\frac{1}{2}d_1 d_2$."},
  {"id":15,"diff":"Medium","q":"Calculate the area of a rhombus featuring diagonals of 20 cm and 15 cm.","opts":["75 cm²","150 cm²","200 cm²","300 cm²"],"ans":"B","exp":"$1/2 \\times 20 \\times 15 = 10 \\times 15 = 150$ cm²."},
  {"id":16,"diff":"Medium","q":"A square agricultural field has a total area of 3136 m². What is its exact side length?","opts":["46 m","56 m","66 m","76 m"],"ans":"B","exp":"$\\sqrt{3136} = 56$ m."},
  {"id":17,"diff":"Medium","q":"To calculate the area of a walking path running uniformly inside a rectangular park, you must logically:","opts":["Add the areas","Subtract the inner rectangle area from the outer rectangle area","Multiply the perimeters","Divide the areas"],"ans":"B","exp":"Subtracting the inner void area from the full outer area isolates the path's area."},
  {"id":18,"diff":"Medium","q":"A specific triangle has an area of 50 cm² and a base measuring 10 cm. What is its altitude (height)?","opts":["5 cm","10 cm","15 cm","20 cm"],"ans":"B","exp":"$50 = 1/2 \\times 10 \\times h \\implies 50 = 5h \\implies h = 10$ cm."},
  {"id":19,"diff":"Medium","q":"A parallelogram and a rectangle share the exact same base and the exact same height. How do their overall areas compare?","opts":["Rectangle is larger","Parallelogram is larger","They are perfectly equal","Cannot determine without angles"],"ans":"C","exp":"Both formulas resolve to $Base \\times Height$. They enclose equal area regardless of the slant."},
  {"id":20,"diff":"Medium","q":"A geometric trapezium features parallel sides $a$ and $b$ and a perpendicular height $h$. Its area is:","opts":["a+b × h","1/2 × (a+b) × h","a × b × h","(a-b) × h"],"ans":"B","exp":"Trapezium area is average of parallel bases multiplied by height: $1/2(a+b)h$."},
  {"id":21,"diff":"Hard","q":"If the length of a rectangle is exactly doubled and the width is simultaneously halved, what happens to the overall area?","opts":["It doubles","It halves","It stays exactly the same","It quadruples"],"ans":"C","exp":"New area $= (2L) \\times (W/2) = L \\times W = $ original area."},
  {"id":22,"diff":"Hard","q":"The precise area of a perfect equilateral triangle featuring a side length $a$ is:","opts":["1/2 a²","(√3/4)a²","(√3/2)a","a²"],"ans":"B","exp":"By Pythagoras, altitude is $(a\\sqrt{3})/2$. Area $= 1/2 \\times a \\times (a\\sqrt{3})/2 = (a^2\\sqrt{3})/4$."},
  {"id":23,"diff":"Hard","q":"If the diagonals of a rhombus are exactly 24 cm and 70 cm, its area is 840 cm². What is the length of one side of the rhombus (utilizing Baudhayana's Theorem)?","opts":["37 cm","47 cm","74 cm","94 cm"],"ans":"A","exp":"Diagonals bisect at right angles. Legs are 12 and 35. $12^2 + 35^2 = 144 + 1225 = 1369$. $\\sqrt{1369} = 37$."},
  {"id":24,"diff":"Hard","q":"A complex polygon is split into two simpler triangles to deduce its total area. This physical deconstruction demonstrates the geometric application of which algebraic concept?","opts":["Distributive property","Associative property","Commutative property","Inverse proportion"],"ans":"A","exp":"Just as $A(B+C) = AB + AC$, spatial area is distributed sum of component shapes."},
  {"id":25,"diff":"Hard","q":"If a perfect square and a perfect circle possess the exact same perimeter, which shape intrinsically encloses the larger area?","opts":["The square","The circle","They are perfectly equal","Depends on the absolute size"],"ans":"B","exp":"A circle is the most efficient shape, enclosing the maximum possible 2D area for any given fixed perimeter."},
  {"id":26,"diff":"Hard","q":"Determine the exact area of a regular hexagon with a side length of 6 cm by dividing it into six equilateral triangles.","opts":["36√3","54√3","72√3","108√3"],"ans":"B","exp":"$6 \\times [(\\sqrt{3}/4) \\times 6^2] = 6 \\times 9\\sqrt{3} = 54\\sqrt{3}$."},
  {"id":27,"diff":"Hard","q":"A rectangular park measures 45 m × 30 m. A path exactly 2.5 m wide is constructed immediately outside the park. Calculate the area of the path alone.","opts":["200 m²","300 m²","400 m²","500 m²"],"ans":"C","exp":"Outer dimensions: $45+5 = 50$, $30+5 = 35$. Outer area $= 1750$. Inner area $= 1350$. Difference $= 400$ m²."},
  {"id":28,"diff":"Hard","q":"If the base of a triangle is increased by exactly 20% and its height is simultaneously decreased by 20%, the new resulting area will:","opts":["Increase by 4%","Decrease by 4%","Stay exactly the same","Decrease by 20%"],"ans":"B","exp":"New Area $= 1/2 \\times (1.2b) \\times (0.8h) = 0.96 \\times (1/2 bh) = 96\\%$ of original area (4% decrease)."},
  {"id":29,"diff":"Hard","q":"Two adjacent sides of a parallelogram are 12 cm and 8 cm. The altitude corresponding to the 12 cm side is 6 cm. What is the precise altitude corresponding to the 8 cm side?","opts":["6 cm","8 cm","9 cm","12 cm"],"ans":"C","exp":"Area $= 12 \\times 6 = 72$. Equating the other base/altitude: $8 \\times h = 72 \\implies h = 9$ cm."},
  {"id":30,"diff":"Hard","q":"The central diagonal of a quadrilateral-shaped field is 24 m, and the perpendiculars dropped onto it from the remaining opposite vertices are 8 m and 13 m respectively. The total area of the field is:","opts":["252 m²","504 m²","126 m²","300 m²"],"ans":"A","exp":"Area of two triangles: $(1/2 \\times 24 \\times 8) + (1/2 \\times 24 \\times 13) = 96 + 156 = 252$ m²."}
]

for i, data in enumerate([ch9, ch10, ch11, ch12, ch13, ch14], 9):
    create_quiz(i, data)
